### ISSUE TITLE
why not implement identity translation module using python?

### ISSUE THREAD

**Issue by pospospos2007** [Azure-Samples/azure-iot-edge-identity-translation-lite#24]
I saw the source code of  identity translation module  is a C# version. Is there a specific reason why we use C# for  identity translation module while other 2 modules (PTM, MQTT) using python?

**Comment by michielvanschaik** [comment]
Main reason is that the implementation of accessing the workload API was more straightforward, but you are free to create a pull-request with an python implementation.
