### ISSUE TITLE
Question about downstream device identity creation

### ISSUE THREAD

**Issue by afroewis** [Azure-Samples/azure-iot-edge-identity-translation-lite#31]
Hi, in this sample, the IoT identity for the downstream device is created in an Azure Function. Is there a reason for this? Why is this not done in the Edge module itself, wouldn't it be easier?

Thanks.

**Comment by katriendg** [comment]
Technically speaking you could do this in the IoT Edge module, but that would pose a security risk as you would need to give a client (the IoT Edge being the client) exceedingly high permissions to be able to interact with the IoT Hub Registry endpoint.

**Comment by afroewis** [comment]
I see. That was my suspicion. 
Thanks for the clarification!
